sudo: required
services: -docker
language: generic
before_install:
  - docker build -t davkir/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davkir/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-115248450297"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
